### ISSUE TITLE
Not able to use in transformers

### ISSUE THREAD

**Issue by sudhir2016** [BobaZooba/shurale#1]
Tried running on transformers as per this code .
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("BobaZooba/Shurale7B-v1-GPTQ")
model = AutoModelForCausalLM.from_pretrained("BobaZooba/Shurale7B-v1-GPTQ")

Got this error PackageNotFoundError: No package metadata was found for auto-gptq

**Comment by bobazooba** [comment]
Hello @sudhir2016!

You just need to install `auto-gptq` to run this model (this is the expected behavior):
```sh
pip3 install auto-gptq
```

**Comment by sudhir2016** [comment]
Thank you @BobaZooba. Model starts loading after installing auto-gptq but runs out of RAM on free tier colab.
